package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-3-8 16:53:39 by Hibernate Tools 4.0.0

import com.sinosoft.util.hibernate.entity.TreeEntitySupport;

/**
 * Company generated by hbm2java
 */
public class Company extends TreeEntitySupport<String, Company> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7334297366396142807L;
	private String name;
	private String comEName;
	private String addressName;
	private String addressEName;
	private String postCode;
	private String phoneNumber;
	private String taxNumber;
	private String faxNumber;
	private String upperComCode;
	private String insurerName;
	private String comAttribute;
	private String comType;
	private String comLevel;
	private String manager;
	private String accountLeader;
	private String cashier;
	private String accountant;
	private String remark;
	private String newComCode;
	private String validStatus;
	private String acntUnit;
	private String articleCode;
	private String accCode;
	private String centerFlag;
	private String outerPayCode;
	private String innerPayCode;
	private String flag;
	private String webAddress;
	private String servicePhone;
	private String reportPhone;
	private String agentCode;
	private String agreementNo;
	private String sysAreaCode;
	private Double comBVisitRate;
	private String printComname;
	private String printAddress;
	private String pringPostCode;
	private String comSign;
	private String motorAreaCode;

	// private Set<FileBoxVersion> fileBoxVersionsForDeptId = new HashSet<FileBoxVersion>(0);
	// private Set<UserGrade> userGrades = new HashSet<UserGrade>(0);
	// private Set<User> users = new HashSet<User>(0);
	// private Set<FileBoxVersion> fileBoxVersionsForCompanyId = new HashSet<FileBoxVersion>(0);
	// private Set<FileBoxVersion> fileBoxVersionsForUpdateDeptId = new HashSet<FileBoxVersion>(0);

	public Company() {
	}

	public String getComCode() {
		return this.id;
	}

	public void setComCode(String comCode) {
		this.id = comCode;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComName() {
		return this.name;
	}

	public void setComName(String comName) {
		this.name = comName;
	}

	public String getComEName() {
		return this.comEName;
	}

	public void setComEName(String comEName) {
		this.comEName = comEName;
	}

	public String getAddressName() {
		return this.addressName;
	}

	public void setAddressName(String addressName) {
		this.addressName = addressName;
	}

	public String getAddressEName() {
		return this.addressEName;
	}

	public void setAddressEName(String addressEName) {
		this.addressEName = addressEName;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getTaxNumber() {
		return this.taxNumber;
	}

	public void setTaxNumber(String taxNumber) {
		this.taxNumber = taxNumber;
	}

	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	public String getUpperComCode() {
		return this.upperComCode;
	}

	public void setUpperComCode(String upperComCode) {
		this.upperComCode = upperComCode;
	}

	public String getInsurerName() {
		return this.insurerName;
	}

	public void setInsurerName(String insurerName) {
		this.insurerName = insurerName;
	}

	public String getComAttribute() {
		return this.comAttribute;
	}

	public void setComAttribute(String comAttribute) {
		this.comAttribute = comAttribute;
	}

	public String getComType() {
		return this.comType;
	}

	public void setComType(String comType) {
		this.comType = comType;
	}

	public String getComLevel() {
		return this.comLevel;
	}

	public void setComLevel(String comLevel) {
		this.comLevel = comLevel;
	}

	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getAccountLeader() {
		return this.accountLeader;
	}

	public void setAccountLeader(String accountLeader) {
		this.accountLeader = accountLeader;
	}

	public String getCashier() {
		return this.cashier;
	}

	public void setCashier(String cashier) {
		this.cashier = cashier;
	}

	public String getAccountant() {
		return this.accountant;
	}

	public void setAccountant(String accountant) {
		this.accountant = accountant;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getNewComCode() {
		return this.newComCode;
	}

	public void setNewComCode(String newComCode) {
		this.newComCode = newComCode;
	}

	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	public String getAcntUnit() {
		return this.acntUnit;
	}

	public void setAcntUnit(String acntUnit) {
		this.acntUnit = acntUnit;
	}

	public String getArticleCode() {
		return this.articleCode;
	}

	public void setArticleCode(String articleCode) {
		this.articleCode = articleCode;
	}

	public String getAccCode() {
		return this.accCode;
	}

	public void setAccCode(String accCode) {
		this.accCode = accCode;
	}

	public String getCenterFlag() {
		return this.centerFlag;
	}

	public void setCenterFlag(String centerflag) {
		this.centerFlag = centerflag;
	}

	public String getOuterPayCode() {
		return this.outerPayCode;
	}

	public void setOuterPayCode(String outerPayCode) {
		this.outerPayCode = outerPayCode;
	}

	public String getInnerPayCode() {
		return this.innerPayCode;
	}

	public void setInnerPayCode(String innerPayCode) {
		this.innerPayCode = innerPayCode;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	public String getServicePhone() {
		return servicePhone;
	}

	public void setServicePhone(String servicePhone) {
		this.servicePhone = servicePhone;
	}

	public String getReportPhone() {
		return reportPhone;
	}

	public void setReportPhone(String reportPhone) {
		this.reportPhone = reportPhone;
	}

	public String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	public String getAgreementNo() {
		return this.agreementNo;
	}

	public void setAgreementNo(String agreementNo) {
		this.agreementNo = agreementNo;
	}

	public String getSysAreaCode() {
		return this.sysAreaCode;
	}

	public void setSysAreaCode(String sysAreaCode) {
		this.sysAreaCode = sysAreaCode;
	}

	public String getPrintComname() {
		return this.printComname;
	}

	public void setPrintComname(String printComname) {
		this.printComname = printComname;
	}

	public String getPrintAddress() {
		return this.printAddress;
	}

	public void setPrintAddress(String printAddress) {
		this.printAddress = printAddress;
	}

	public String getPringPostCode() {
		return this.pringPostCode;
	}

	public void setPringPostCode(String pringPostCode) {
		this.pringPostCode = pringPostCode;
	}

	public String getComSign() {
		return this.comSign;
	}

	public void setComSign(String comSign) {
		this.comSign = comSign;
	}

	public String getMotorAreaCode() {
		return this.motorAreaCode;
	}

	public void setMotorAreaCode(String motorAreaCode) {
		this.motorAreaCode = motorAreaCode;
	}

	public Double getComBVisitRate() {
		return comBVisitRate;
	}

	public void setComBVisitRate(Double comBVisitRate) {
		this.comBVisitRate = comBVisitRate;
	}

}
