package com.sinosoft.efiling.hibernate.entity;

import java.io.Serializable;

// Generated 2013-3-8 17:57:18 by Hibernate Tools 4.0.0

/**
 * GradeTaskId generated by hbm2java
 */
public class GradeTaskId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -717486970919626615L;
	private String gradeCode;
	private String taskCode;

	public GradeTaskId() {
	}

	public GradeTaskId(String gradeCode, String taskCode) {
		this.gradeCode = gradeCode;
		this.taskCode = taskCode;
	}

	public String getGradeCode() {
		return this.gradeCode;
	}

	public void setGradeCode(String gradeCode) {
		this.gradeCode = gradeCode;
	}

	public String getTaskCode() {
		return this.taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GradeTaskId))
			return false;
		GradeTaskId castOther = (GradeTaskId) other;

		return ((this.getGradeCode() == castOther.getGradeCode()) || (this.getGradeCode() != null
				&& castOther.getGradeCode() != null && this.getGradeCode().equals(castOther.getGradeCode())))
				&& ((this.getTaskCode() == castOther.getTaskCode()) || (this.getTaskCode() != null
						&& castOther.getTaskCode() != null && this.getTaskCode().equals(castOther.getTaskCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGradeCode() == null ? 0 : this.getGradeCode().hashCode());
		result = 37 * result + (getTaskCode() == null ? 0 : this.getTaskCode().hashCode());
		return result;
	}

}
