package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-3-8 17:57:18 by Hibernate Tools 4.0.0

import com.sinosoft.util.hibernate.entity.TreeEntitySupport;

/**
 * Menu generated by hbm2java
 */
public class Menu extends TreeEntitySupport<String, Menu> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3326356596340446041L;
	private String name;
	private Task task;
	private long menuLevel;
	private String systemCode;
	private String menuEName;
	private String url;
	private String target;
	private long displayNo;
	private String image;
	private String imageExpand;
	private String imageCollapse;
	private String iconExpand;
	private String iconCollapse;
	private String validStatus;
	private String remark;
	private String flag;
	private String permitRiskClass;
	private String exceptRiskCode;
	private String exceptRiskClass;
	private String permitRiskCode;
	private String checkClass;

	public Menu() {
	}

	public Task getTask() {
		return task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getMenuLevel() {
		return menuLevel;
	}

	public void setMenuLevel(long menuLevel) {
		this.menuLevel = menuLevel;
	}

	public String getSystemCode() {
		return systemCode;
	}

	public void setSystemCode(String systemCode) {
		this.systemCode = systemCode;
	}

	public String getMenuEName() {
		return menuEName;
	}

	public void setMenuEName(String menuEName) {
		this.menuEName = menuEName;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getTarget() {
		return target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public long getDisplayNo() {
		return displayNo;
	}

	public void setDisplayNo(long displayNo) {
		this.displayNo = displayNo;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getImageExpand() {
		return imageExpand;
	}

	public void setImageExpand(String imageExpand) {
		this.imageExpand = imageExpand;
	}

	public String getImageCollapse() {
		return imageCollapse;
	}

	public void setImageCollapse(String imageCollapse) {
		this.imageCollapse = imageCollapse;
	}

	public String getIconExpand() {
		return iconExpand;
	}

	public void setIconExpand(String iconExpand) {
		this.iconExpand = iconExpand;
	}

	public String getIconCollapse() {
		return iconCollapse;
	}

	public void setIconCollapse(String iconCollapse) {
		this.iconCollapse = iconCollapse;
	}

	public String getValidStatus() {
		return validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getPermitRiskClass() {
		return permitRiskClass;
	}

	public void setPermitRiskClass(String permitRiskClass) {
		this.permitRiskClass = permitRiskClass;
	}

	public String getExceptRiskCode() {
		return exceptRiskCode;
	}

	public void setExceptRiskCode(String exceptRiskCode) {
		this.exceptRiskCode = exceptRiskCode;
	}

	public String getExceptRiskClass() {
		return exceptRiskClass;
	}

	public void setExceptRiskClass(String exceptRiskClass) {
		this.exceptRiskClass = exceptRiskClass;
	}

	public String getPermitRiskCode() {
		return permitRiskCode;
	}

	public void setPermitRiskCode(String permitRiskCode) {
		this.permitRiskCode = permitRiskCode;
	}

	public String getCheckClass() {
		return checkClass;
	}

	public void setCheckClass(String checkClass) {
		this.checkClass = checkClass;
	}

}
