package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-3-8 17:57:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.sinosoft.util.hibernate.entity.TreeEntitySupport;

/**
 * Task generated by hbm2java
 */
public class Task extends TreeEntitySupport<String, Task> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4155958425656899640L;
	private String name;
	private String remark;
	private String flag;
	private String taskEName;
	private Set<Menu> menus = new HashSet<Menu>(0);

	// private Set<UserGradeTask> userGradeTasks = new HashSet<UserGradeTask>(0);

	public Task() {
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getTaskEName() {
		return this.taskEName;
	}

	public void setTaskEName(String taskEName) {
		this.taskEName = taskEName;
	}

	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}
}
