package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-3-8 17:57:18 by Hibernate Tools 4.0.0

import com.sinosoft.util.hibernate.entity.EntitySupport;

/**
 * UserGradeTask generated by hbm2java
 */
public class UserGradeTask extends EntitySupport<UserGradeTaskId> {
	/**
	 * 
	 */
	private static final long serialVersionUID = -7173060351016511147L;
	private UserGrade userGrade;
	private Task task;
	private String grantLevel;
	private String grantValue;
	private String value;
	private String remark;
	private String flag;

	public UserGradeTask() {
	}

	public UserGradeTask(UserGradeTaskId id, UserGrade userGrade, Task task, String value) {
		this.id = id;
		this.userGrade = userGrade;
		this.task = task;
		this.value = value;
	}

	public UserGradeTask(UserGradeTaskId id, UserGrade userGrade, Task task, String grantLevel, String grantValue,
			String value, String remark, String flag) {
		this.id = id;
		this.userGrade = userGrade;
		this.task = task;
		this.grantLevel = grantLevel;
		this.grantValue = grantValue;
		this.value = value;
		this.remark = remark;
		this.flag = flag;
	}

	public UserGradeTaskId getId() {
		return this.id;
	}

	public void setId(UserGradeTaskId id) {
		this.id = id;
	}

	public UserGrade getUserGrade() {
		return this.userGrade;
	}

	public void setUserGrade(UserGrade userGrade) {
		this.userGrade = userGrade;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public String getGrantLevel() {
		return this.grantLevel;
	}

	public void setGrantLevel(String grantLevel) {
		this.grantLevel = grantLevel;
	}

	public String getGrantValue() {
		return this.grantValue;
	}

	public void setGrantValue(String grantValue) {
		this.grantValue = grantValue;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
