package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-3-8 17:57:18 by Hibernate Tools 4.0.0

/**
 * UserGradePowerId generated by hbm2java
 */
public class UserGradePowerId extends UserGradeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6044723309058022156L;
	// private String comCode;
	// private String userCode;
	// private String gradeCode;
	private long serialno;

	public UserGradePowerId() {
	}

	public UserGradePowerId(String comCode, String userCode, String gradeCode, long serialno) {
		this.comCode = comCode;
		this.userCode = userCode;
		this.gradeCode = gradeCode;
		this.serialno = serialno;
	}

	public long getSerialno() {
		return this.serialno;
	}

	public void setSerialno(long serialno) {
		this.serialno = serialno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserGradePowerId))
			return false;
		UserGradePowerId castOther = (UserGradePowerId) other;

		return ((this.getComCode() == castOther.getComCode()) || (this.getComCode() != null
				&& castOther.getComCode() != null && this.getComCode().equals(castOther.getComCode())))
				&& ((this.getUserCode() == castOther.getUserCode()) || (this.getUserCode() != null
						&& castOther.getUserCode() != null && this.getUserCode().equals(castOther.getUserCode())))
				&& ((this.getGradeCode() == castOther.getGradeCode()) || (this.getGradeCode() != null
						&& castOther.getGradeCode() != null && this.getGradeCode().equals(castOther.getGradeCode())))
				&& (this.getSerialno() == castOther.getSerialno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getComCode() == null ? 0 : this.getComCode().hashCode());
		result = 37 * result + (getUserCode() == null ? 0 : this.getUserCode().hashCode());
		result = 37 * result + (getGradeCode() == null ? 0 : this.getGradeCode().hashCode());
		result = 37 * result + (int) this.getSerialno();
		return result;
	}

}
