package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-3-8 17:57:18 by Hibernate Tools 4.0.0

/**
 * UserGradeTaskId generated by hbm2java
 */
public class UserGradeTaskId extends UserGradeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8642899308278491945L;
	// private String comCode;
	// private String userCode;
	// private String gradeCode;
	private String taskCode;

	public UserGradeTaskId() {
	}

	public UserGradeTaskId(String comCode, String userCode, String gradeCode, String taskCode) {
		this.comCode = comCode;
		this.userCode = userCode;
		this.gradeCode = gradeCode;
		this.taskCode = taskCode;
	}

	public String getTaskCode() {
		return this.taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserGradeTaskId))
			return false;
		UserGradeTaskId castOther = (UserGradeTaskId) other;

		return ((this.getComCode() == castOther.getComCode()) || (this.getComCode() != null
				&& castOther.getComCode() != null && this.getComCode().equals(castOther.getComCode())))
				&& ((this.getUserCode() == castOther.getUserCode()) || (this.getUserCode() != null
						&& castOther.getUserCode() != null && this.getUserCode().equals(castOther.getUserCode())))
				&& ((this.getGradeCode() == castOther.getGradeCode()) || (this.getGradeCode() != null
						&& castOther.getGradeCode() != null && this.getGradeCode().equals(castOther.getGradeCode())))
				&& ((this.getTaskCode() == castOther.getTaskCode()) || (this.getTaskCode() != null
						&& castOther.getTaskCode() != null && this.getTaskCode().equals(castOther.getTaskCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getComCode() == null ? 0 : this.getComCode().hashCode());
		result = 37 * result + (getUserCode() == null ? 0 : this.getUserCode().hashCode());
		result = 37 * result + (getGradeCode() == null ? 0 : this.getGradeCode().hashCode());
		result = 37 * result + (getTaskCode() == null ? 0 : this.getTaskCode().hashCode());
		return result;
	}

}
