package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-3-8 17:57:18 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.sinosoft.util.hibernate.entity.EntitySupport;

/**
 * User generated by hbm2java
 */
public class User extends EntitySupport<String> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1026482579836691953L;

	protected Company department;

	protected String no;
	protected String name;
	protected String password;
	protected String seal;
	protected Date passwordSetDate;
	protected Date passwordExpireDate;
	protected String makeCom;
	protected String accountCode;
	protected String phone;
	protected String mobile;
	protected String address;
	protected String postCode;
	protected String email;
	protected String userFlag;
	protected String loginSystem;
	protected String newUserCode;
	protected String validStatus;
	protected String articleCode;
	protected String flag;
	protected Integer maxOverdueCount;
	protected Double maxOverdueFee;
	protected String macAddress;
	protected String businessFlag;
	protected String agentCode;

	protected Set<UserGrade> userGrades = new HashSet<UserGrade>(0);

	// protected Set<FileBoxVersion> fileBoxVersionsForUserId = new HashSet<FileBoxVersion>(0);
	// protected Set<FileBoxVersion> fileBoxVersionsForUpdateUserId = new HashSet<FileBoxVersion>(0);

	public User() {
	}

	public Company getDepartment() {
		return department;
	}

	public void setDepartment(Company department) {
		this.department = department;
	}

	public String getNo() {
		return no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSeal() {
		return seal;
	}

	public void setSeal(String seal) {
		this.seal = seal;
	}

	public Date getPasswordSetDate() {
		return passwordSetDate;
	}

	public void setPasswordSetDate(Date passwordSetDate) {
		this.passwordSetDate = passwordSetDate;
	}

	public Date getPasswordExpireDate() {
		return passwordExpireDate;
	}

	public void setPasswordExpireDate(Date passwordExpireDate) {
		this.passwordExpireDate = passwordExpireDate;
	}

	public String getMakeCom() {
		return makeCom;
	}

	public void setMakeCom(String makeCom) {
		this.makeCom = makeCom;
	}

	public String getAccountCode() {
		return accountCode;
	}

	public void setAccountCode(String accountCode) {
		this.accountCode = accountCode;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostCode() {
		return postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUserFlag() {
		return userFlag;
	}

	public void setUserFlag(String userFlag) {
		this.userFlag = userFlag;
	}

	public String getLoginSystem() {
		return loginSystem;
	}

	public void setLoginSystem(String loginSystem) {
		this.loginSystem = loginSystem;
	}

	public String getNewUserCode() {
		return newUserCode;
	}

	public void setNewUserCode(String newUserCode) {
		this.newUserCode = newUserCode;
	}

	public String getValidStatus() {
		return validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	public String getArticleCode() {
		return articleCode;
	}

	public void setArticleCode(String articleCode) {
		this.articleCode = articleCode;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Integer getMaxOverdueCount() {
		return maxOverdueCount;
	}

	public void setMaxOverdueCount(Integer maxOverdueCount) {
		this.maxOverdueCount = maxOverdueCount;
	}

	public Double getMaxOverdueFee() {
		return maxOverdueFee;
	}

	public void setMaxOverdueFee(Double maxOverdueFee) {
		this.maxOverdueFee = maxOverdueFee;
	}

	public String getMacAddress() {
		return macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public String getBusinessFlag() {
		return businessFlag;
	}

	public void setBusinessFlag(String businessFlag) {
		this.businessFlag = businessFlag;
	}

	public String getAgentCode() {
		return agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	public Set<UserGrade> getUserGrades() {
		return userGrades;
	}

	public void setUserGrades(Set<UserGrade> userGrades) {
		this.userGrades = userGrades;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
