package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-3-8 17:57:18 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.sinosoft.util.hibernate.entity.EntitySupport;

/**
 * UserGrade generated by hbm2java
 */
public class UserGrade extends EntitySupport<UserGradeId> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1674678453057906939L;
	private Company company;
	private Grade grade;
	private User user;

	private Date invalidDate;
	private String validStatus;
	private String remark;
	private String flag;

	private Set<UserGradePower> userGradePowers = new HashSet<UserGradePower>(0);
	private Set<UserGradeTask> userGradeTasks = new HashSet<UserGradeTask>(0);

	public UserGrade() {
	}

	public UserGrade(UserGradeId id, Company company, Grade grade, User user, String validStatus) {
		this.id = id;
		this.company = company;
		this.grade = grade;
		this.user = user;
		this.validStatus = validStatus;
	}

	public UserGrade(UserGradeId id, Company company, Grade grade, User user, Date invalidDate, String validStatus,
			String remark, String flag, Set<UserGradePower> userGradePowers, Set<UserGradeTask> userGradeTasks) {
		this.id = id;
		this.company = company;
		this.grade = grade;
		this.user = user;
		this.invalidDate = invalidDate;
		this.validStatus = validStatus;
		this.remark = remark;
		this.flag = flag;
		this.userGradePowers = userGradePowers;
		this.userGradeTasks = userGradeTasks;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getInvalidDate() {
		return this.invalidDate;
	}

	public void setInvalidDate(Date invalidDate) {
		this.invalidDate = invalidDate;
	}

	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Set<UserGradePower> getUserGradePowers() {
		return this.userGradePowers;
	}

	public void setUserGradePowers(Set<UserGradePower> userGradePowers) {
		this.userGradePowers = userGradePowers;
	}

	public Set<UserGradeTask> getUserGradeTasks() {
		return this.userGradeTasks;
	}

	public void setUserGradeTasks(Set<UserGradeTask> userGradeTasks) {
		this.userGradeTasks = userGradeTasks;
	}

}
