package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-3-8 17:57:18 by Hibernate Tools 4.0.0

import java.io.Serializable;

/**
 * UserGradeId generated by hbm2java
 */
public class UserGradeId implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 6328779845564012758L;
	protected String comCode;
	protected String userCode;
	protected String gradeCode;

	public UserGradeId() {
	}

	public UserGradeId(String comCode, String userCode, String gradeCode) {
		this.comCode = comCode;
		this.userCode = userCode;
		this.gradeCode = gradeCode;
	}

	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getGradeCode() {
		return this.gradeCode;
	}

	public void setGradeCode(String gradeCode) {
		this.gradeCode = gradeCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserGradeId))
			return false;
		UserGradeId castOther = (UserGradeId) other;

		return ((this.getComCode() == castOther.getComCode()) || (this.getComCode() != null
				&& castOther.getComCode() != null && this.getComCode().equals(castOther.getComCode())))
				&& ((this.getUserCode() == castOther.getUserCode()) || (this.getUserCode() != null
						&& castOther.getUserCode() != null && this.getUserCode().equals(castOther.getUserCode())))
				&& ((this.getGradeCode() == castOther.getGradeCode()) || (this.getGradeCode() != null
						&& castOther.getGradeCode() != null && this.getGradeCode().equals(castOther.getGradeCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getComCode() == null ? 0 : this.getComCode().hashCode());
		result = 37 * result + (getUserCode() == null ? 0 : this.getUserCode().hashCode());
		result = 37 * result + (getGradeCode() == null ? 0 : this.getGradeCode().hashCode());
		return result;
	}

}
